### ISSUE TITLE
배너 API에서 추가로 필요한내용

### ISSUE THREAD

**Issue by Sangjun-man** [EndlessCreation/EC-Advance-2021-Team2_BackEnd#2]
![image](https://user-images.githubusercontent.com/66112027/141076577-1313da7b-50d2-48a0-b327-ab44b4b75424.png)

우측하단보면 # @ 뒤에 텍스트가 없는데

![image](https://user-images.githubusercontent.com/66112027/141076591-8920201e-3e4b-478f-85bb-c45f81010352.png)

tag값과 keyword 값도 같이 보내줘야 배너에 띄울수있을거같습니다~

**Comment by qudtjs0753** [comment]
태그 키워드값 같이 보내도록 수정 완료했습니다.
