### ISSUE TITLE
날짜 필터링 관련 이슈

### ISSUE THREAD

**Issue by Sangjun-man** [EndlessCreation/EC-Advance-2021-Team2_BackEnd#5]
![image](https://user-images.githubusercontent.com/66112027/141263462-91e01ad5-8112-425e-bac9-296a0c2ef7e4.png)

이전 ~ 10일까지 필터링 한 모습 , 10일자 post값이 오지 않음

![image](https://user-images.githubusercontent.com/66112027/141263489-01f74949-ab8b-44bf-ba91-07a1d74e7f4f.png)

10일 ~~ 11일까지 필터링 한 모습

![image](https://user-images.githubusercontent.com/66112027/141263517-efad43b1-94ed-40f1-b5c8-deb0bcf527b0.png)

11일~18일 까지 필터링 한 모습, 10일자 post 값이  같이 옴

콘솔에 보내주는 date값 = { 시작날짜 00:00:00 , 끝날짜 23:59:59}
으로 보내주고 있는데 필터링해주는 로직에 문제가 있는것 같습니다

**Comment by qudtjs0753** [comment]
ISO format으로 보내주시면 되겠습니다.
